### ISSUE TITLE
Option to prioritize system default

### ISSUE THREAD

**Issue by ollebergkvist** [saadeghi/theme-change#19]
Is there a way to prioritize the system default somehow?
E.g. When a user who has selected dark mode in their system preferences, when entering
the page the plugin defaults to dark mode?

**Comment by rafifos** [comment]
Since a theme can be any string (for example: `cyberpunk`, in [daisyUI](https://daisyui.com/docs/themes/)), then this also implies that there would be an option to set which theme is treated as `light` and which is treated as `dark`? If so, how would that be configured?

**Comment by saadeghi** [comment]
> E.g. When a user who has selected dark mode in their system preferences, when entering
> the page the plugin defaults to dark mode?

That depends on the CSS. daisyUI does this. by default, `dark` theme on daisyUI will be activated if the OS is on dark mode.  

`theme-change` does not care about the CSS.  
This is all `theme-change` does:
- Change CSS theme using `button`, `toggle` or a `<select>`
- It saves chosen theme in browser and uses it again when page reloads

So, by default, if no theme is chosen by user and your CSS has a style for `@media (prefers-color-scheme: dark)` (daisyUI does) the dark style would apply. otherwise it would be light.  
And if user have chose a theme, the theme name would be inside Local Storage and `theme-change` will put that chosen theme in `<html data-theme="______">`.
