### ISSUE TITLE
Bug when the ThemeChange dropdown is used with the stats and table

### ISSUE THREAD

**Issue by woss** [saadeghi/theme-change#24]
This screenshot illustrates two bugs 

1.  the text on the top is the `Stats` from the daisy ui
2. the second is the `Table` header  from the daisyui

<img width="174" alt="image" src="https://user-images.githubusercontent.com/80440/198234403-a1b8071d-e557-4efb-bbfa-d8a9a5888ebe.png">

I've searched for potential issues with the z-index, increasing it doesn't solve the issue.  I've created another Dropdown and it has the same problem.

**Comment by saadeghi** [comment]
I can't see this issue.  
Which page is this from?  
are you using any software or browser plugin that may manipulate CSS or HTML on web pages?

**Comment by woss** [comment]
Hi, it is one of my projects. sorry if wasn't clear about it. 
The issue is gone now by making sure that the `navbar` and `sidebar` have z-index larger than 50. I also observed that if the navbar has opacity this happens as well

**Comment by saadeghi** [comment]
I have to close this because this is not an issue about `theme-change`.  
`theme-change` package has one job: changing the theme on Local Storage and on the `data-theme` attribute.  
Anything about the z-index or layout, would depend on the CSS or HTML.  

And I can't even help you with that unless you provide a sample repo or code example.
