### ISSUE TITLE
Dark mode loaded briefly on each page load before presenting stored theme

### ISSUE THREAD

**Issue by newbelaravel** [saadeghi/theme-change#26]
Hello all,

I am using this package in conjunction with DaisyUI. I have a button-based theme switcher. Basically, one button sets day theme, and other sets dark theme. The selected theme is stored locally correctly. The problem is that, with day theme selected, for every page load, I see dark theme very briefly. I made a gif:
![toggle theme](https://user-images.githubusercontent.com/7984653/200119278-272873c9-d37a-4fc8-81a0-886ca54a948b.gif)

I think that the problem is that the script of the package is getting executed long after page is loaded. It happens both installing package through NPM and using it with CDN. Also I have dark theme on windows on this local envirnonment. This happens usinf firefox. If I use Chrome, it happens the other way around. For every page load I get a glimpse of dark theme (when browsing with day theme).
Theme switcher code:
```   
<button data-set-theme="autumn" data-act-class="ACTIVECLASS">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" />
    </svg>
</button>
<button data-set-theme="dark" data-act-class="ACTIVECLASS">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z" />
    </svg>
</button>
```
Tailwind config:
```
module.exports = {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      "autumn",
      "dark",
    ],
  },
  plugins: [
    require('@tailwindcss/typography'),
    require("daisyui"),
    require('tailwind-scrollbar'),
  ],
}
```
DaisyUI version: 2.38
TailwindUI version: 3.2.1

**Comment by saadeghi** [comment]
As you said, this happens because the JS is getting executed after the page loads.  
The page loads, HTML and CSS show up with the default theme then JS loads and reads local storage and the applies the chosen theme.
I can't do anything about it in the package itself because the priority of loading JS code depends on how we use it or where the framework puts it. And this behavior is expected for `theme-change` or any client-side theme management code because JS runs after CSS and HTML loads.


So there are 3 options:
- Ignore the flaw that for a second, the default theme shows up on a fresh reload.
- Instead of using `theme-change` or any client-side theme management code, save the chosen theme on server so when HTML loads, it load with the chosen theme, not the default one.
- Put [`theme-change` CDN code](https://unpkg.com/theme-change@2.2.0/index.js) in `<head>` before any other asset. This way the JS file will load as a critical code and JS will read the chosen theme from local storage and applies it to `<html>` tag before any CSS loads. The downside of this solution would probably be a slightly lower lighthouse score because showing CSS and HTML will be blocked unless the `theme-change` JS loads. It's a very small code but still...

Let me know if you have any questions.

**Comment by newbelaravel** [comment]
Thank you very much for the explanation, it was very clear. I'll go with the back-end option. 

EDIT: Already implemented it with a cookie and works fantastic.
