### ISSUE TITLE
support for qwik

### ISSUE THREAD

**Issue by RBleyenberg** [saadeghi/theme-change#36]
installed it and pretty must used the same code as daisy ui but bit of refactor on the template.
in order for it to work i'm using it within useVisibleTask$ so that document is found.

as of now the template will default to dark and sets the string inside localstorage if we choose light for example then it will work but...

after each route change or page refresh it will default to dark and after 1 second will go to light if set in localstorage ofcourse, so a flikker will happen everytime -_-

If have tried to put the themeChange(false) in the root but it keep occurring .

I think the problem is that qwik renders serversite first and spits the template out, after that with useVisibleTask$ you have access to document and set the theme correct.  

so maybe it's just that for qwik this package isn't the easy solutions and can't work due to the way qwik handles templating ?? I'm just wondering.

Cheers

**Comment by saadeghi** [comment]
I don't have much experience with Qwik but is there a way to run a script before the page load? Maybe [`useTask$()`](https://qwik.builder.io/docs/components/lifecycle/#usetask)?

**Comment by RBleyenberg** [comment]
issue is bigger then that but there is open issue on qwik

#https://github.com/BuilderIO/qwik/issues/3391

so will just keep track of that one for now.

Thanks

**Comment by saadeghi** [comment]
Basically with `theme-change` or any other client side theme management code, it is expected to see a flicker because first the HTML loads, then the CSS loads (and applies the default theme) then JS loads and reads the local storage and applies the chosen theme. To completely prevent this flaw, there are 2 ways:  
1. Instead of using a client-side theme management code like this and storing the chosen theme in the browser local storage, use server and store each user's chosen theme in the database.
2. Making sure `theme-change` script loads and runs before every other code:
    - If you use the CDN address instead of the NPM package and put it in the `<head>` before everything else, the JS code can apply the chosen theme before the page render
    - If your JS framework has way to use the function before rendering the page (or component) you can make sure that the chosen theme is getting applied before anything else

**Comment by RBleyenberg** [comment]
Thanks,

i've put the theme in the user object on the backend and then the data-theme={getUserContext.theme} as close to the root as possible and it all works just fine atm.

thanks for the lightbulb moment
