### ISSUE TITLE
toggle doesn't work on mobile PWA

### ISSUE THREAD

**Issue by beebase** [saadeghi/theme-change#6]
Can someone confirm that the toggle script doesn't work on mobile? (chrome/android)

**Comment by saadeghi** [comment]
@beebase can you please provide an example repo or a live example so I can see what's the issue?

**Comment by beebase** [comment]
My bad. I thought I was using JIT, but I wasn't.
After safelisting "data-theme" all was fine.

Sorry for that.



[daisyui docs](https://daisyui.com/docs/default-themes/)
```
If you're not using Tailwind JIT 
You need to safelist data-theme attribute so PurgeCSS doesn't purge it

module.exports = {

    purge: {
      content: ['yourfiles/**/*.html'],
      options: {
        safelist: [
          /data-theme$/,
        ]
      },
    },

  }
````

**Comment by d3tr0id** [comment]
Hi, have you managed to get this working with the daisyUI toggle? Because in my case everytime I refresh the window, the toggle gets reset, but not reinitialized so that it shows the current state

https://user-images.githubusercontent.com/38083027/169801075-4b4bf031-b745-42df-96f1-8fcd686743d1.mov

.
